version: "3.9"
services:
  proof_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - proof_volume:/var/lib/postgresql
volumes:
  proof_volume:
